include: package:pedantic/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    unrelated_type_equality_checks: true
    prefer_single_quotes: false
    prefer_double_quotes: false
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    unnecessary_parenthesis: true
    prefer_final_locals: true
    prefer_initializing_formals: true
    avoid_void_async: true
    await_only_futures: true
    avoid_empty_else: true
    empty_statements: true
    avoid_classes_with_only_static_members: true
    list_remove_unrelated_type: true
    avoid_relative_lib_imports: true
    implementation_imports: true
    empty_catches: true
    empty_constructor_bodies: true
